# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ocrSubmit.ui'
#
# Created: Tue Apr 21 00:16:27 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_OpenCloudRenderSubmit(object):
    def setupUi(self, OpenCloudRenderSubmit):
        OpenCloudRenderSubmit.setObjectName("OpenCloudRenderSubmit")
        OpenCloudRenderSubmit.resize(1370, 346)
        OpenCloudRenderSubmit.setAcceptDrops(True)
        self.centralwidget = QtGui.QWidget(OpenCloudRenderSubmit)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 1370, 221))
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.submissionTab = QtGui.QWidget()
        self.submissionTab.setObjectName("submissionTab")
        self.arnoldVersionComboBox = QtGui.QComboBox(self.submissionTab)
        self.arnoldVersionComboBox.setEnabled(False)
        self.arnoldVersionComboBox.setGeometry(QtCore.QRect(745, 30, 121, 26))
        self.arnoldVersionComboBox.setObjectName("arnoldVersionComboBox")
        self.vrayVersionComboBox = QtGui.QComboBox(self.submissionTab)
        self.vrayVersionComboBox.setGeometry(QtCore.QRect(1045, 30, 121, 26))
        self.vrayVersionComboBox.setObjectName("vrayVersionComboBox")
        self.submitScenesButton = QtGui.QPushButton(self.submissionTab)
        self.submitScenesButton.setGeometry(QtCore.QRect(1175, 110, 170, 30))
        self.submitScenesButton.setObjectName("submitScenesButton")
        self.mantraVersionComboBox = QtGui.QComboBox(self.submissionTab)
        self.mantraVersionComboBox.setEnabled(False)
        self.mantraVersionComboBox.setGeometry(QtCore.QRect(405, 30, 121, 26))
        self.mantraVersionComboBox.setObjectName("mantraVersionComboBox")
        self.syncAssetsButton = QtGui.QPushButton(self.submissionTab)
        self.syncAssetsButton.setGeometry(QtCore.QRect(1175, 70, 170, 30))
        self.syncAssetsButton.setObjectName("syncAssetsButton")
        self.scenesTableView = QtGui.QTableView(self.submissionTab)
        self.scenesTableView.setGeometry(QtCore.QRect(5, 60, 1161, 120))
        self.scenesTableView.setAcceptDrops(True)
        self.scenesTableView.setObjectName("scenesTableView")
        self.addScenesButton = QtGui.QPushButton(self.submissionTab)
        self.addScenesButton.setEnabled(False)
        self.addScenesButton.setGeometry(QtCore.QRect(1175, 30, 170, 30))
        self.addScenesButton.setObjectName("addScenesButton")
        self.arnoldVersionLabel = QtGui.QLabel(self.submissionTab)
        self.arnoldVersionLabel.setEnabled(False)
        self.arnoldVersionLabel.setGeometry(QtCore.QRect(595, 35, 141, 20))
        self.arnoldVersionLabel.setObjectName("arnoldVersionLabel")
        self.dragDropOnlyLabel = QtGui.QLabel(self.submissionTab)
        self.dragDropOnlyLabel.setGeometry(QtCore.QRect(1185, 10, 151, 20))
        self.dragDropOnlyLabel.setObjectName("dragDropOnlyLabel")
        self.vrayVersionLabel = QtGui.QLabel(self.submissionTab)
        self.vrayVersionLabel.setGeometry(QtCore.QRect(895, 35, 141, 20))
        self.vrayVersionLabel.setObjectName("vrayVersionLabel")
        self.syncImagesButton = QtGui.QPushButton(self.submissionTab)
        self.syncImagesButton.setGeometry(QtCore.QRect(1175, 150, 170, 30))
        self.syncImagesButton.setObjectName("syncImagesButton")
        self.mantraVersionLabel = QtGui.QLabel(self.submissionTab)
        self.mantraVersionLabel.setEnabled(False)
        self.mantraVersionLabel.setGeometry(QtCore.QRect(245, 35, 151, 20))
        self.mantraVersionLabel.setObjectName("mantraVersionLabel")
        self.tabWidget.addTab(self.submissionTab, "")
        self.repoTab = QtGui.QWidget()
        self.repoTab.setObjectName("repoTab")
        self.syncVrayRepoButton = QtGui.QPushButton(self.repoTab)
        self.syncVrayRepoButton.setGeometry(QtCore.QRect(680, 30, 141, 20))
        self.syncVrayRepoButton.setObjectName("syncVrayRepoButton")
        self.vrayRepoRootDirLineEdit = QtGui.QLineEdit(self.repoTab)
        self.vrayRepoRootDirLineEdit.setGeometry(QtCore.QRect(140, 30, 531, 20))
        self.vrayRepoRootDirLineEdit.setObjectName("vrayRepoRootDirLineEdit")
        self.vrayRepoRootDirLabel = QtGui.QLabel(self.repoTab)
        self.vrayRepoRootDirLabel.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.vrayRepoRootDirLabel.setObjectName("vrayRepoRootDirLabel")
        self.houdiniRepoRootDirLineEdit = QtGui.QLineEdit(self.repoTab)
        self.houdiniRepoRootDirLineEdit.setGeometry(QtCore.QRect(140, 60, 531, 20))
        self.houdiniRepoRootDirLineEdit.setObjectName("houdiniRepoRootDirLineEdit")
        self.syncHoudiniRepoButton = QtGui.QPushButton(self.repoTab)
        self.syncHoudiniRepoButton.setGeometry(QtCore.QRect(680, 60, 141, 20))
        self.syncHoudiniRepoButton.setObjectName("syncHoudiniRepoButton")
        self.houdiniRepoRootDirLabel = QtGui.QLabel(self.repoTab)
        self.houdiniRepoRootDirLabel.setGeometry(QtCore.QRect(20, 60, 121, 20))
        self.houdiniRepoRootDirLabel.setObjectName("houdiniRepoRootDirLabel")
        self.arnoldRepoRootDirLineEdit = QtGui.QLineEdit(self.repoTab)
        self.arnoldRepoRootDirLineEdit.setGeometry(QtCore.QRect(140, 90, 531, 20))
        self.arnoldRepoRootDirLineEdit.setObjectName("arnoldRepoRootDirLineEdit")
        self.syncArnoldRepoButton = QtGui.QPushButton(self.repoTab)
        self.syncArnoldRepoButton.setGeometry(QtCore.QRect(680, 90, 141, 20))
        self.syncArnoldRepoButton.setObjectName("syncArnoldRepoButton")
        self.arnoldRepoRootDirLabel = QtGui.QLabel(self.repoTab)
        self.arnoldRepoRootDirLabel.setGeometry(QtCore.QRect(20, 90, 121, 20))
        self.arnoldRepoRootDirLabel.setObjectName("arnoldRepoRootDirLabel")
        self.vrayRepoExcludesLineEdit = QtGui.QLineEdit(self.repoTab)
        self.vrayRepoExcludesLineEdit.setGeometry(QtCore.QRect(890, 30, 465, 20))
        self.vrayRepoExcludesLineEdit.setObjectName("vrayRepoExcludesLineEdit")
        self.vrayRepoExcludesLabel = QtGui.QLabel(self.repoTab)
        self.vrayRepoExcludesLabel.setGeometry(QtCore.QRect(830, 30, 61, 20))
        self.vrayRepoExcludesLabel.setObjectName("vrayRepoExcludesLabel")
        self.vrayRepoExcludesLineEdit_2 = QtGui.QLineEdit(self.repoTab)
        self.vrayRepoExcludesLineEdit_2.setGeometry(QtCore.QRect(890, 60, 465, 20))
        self.vrayRepoExcludesLineEdit_2.setObjectName("vrayRepoExcludesLineEdit_2")
        self.vrayRepoExcludesLabel_2 = QtGui.QLabel(self.repoTab)
        self.vrayRepoExcludesLabel_2.setGeometry(QtCore.QRect(830, 60, 61, 20))
        self.vrayRepoExcludesLabel_2.setObjectName("vrayRepoExcludesLabel_2")
        self.vrayRepoExcludesLineEdit_3 = QtGui.QLineEdit(self.repoTab)
        self.vrayRepoExcludesLineEdit_3.setGeometry(QtCore.QRect(890, 90, 465, 20))
        self.vrayRepoExcludesLineEdit_3.setObjectName("vrayRepoExcludesLineEdit_3")
        self.vrayRepoExcludesLabel_3 = QtGui.QLabel(self.repoTab)
        self.vrayRepoExcludesLabel_3.setGeometry(QtCore.QRect(830, 90, 61, 20))
        self.vrayRepoExcludesLabel_3.setObjectName("vrayRepoExcludesLabel_3")
        self.tabWidget.addTab(self.repoTab, "")
        self.repoBucketName = QtGui.QLineEdit(self.centralwidget)
        self.repoBucketName.setGeometry(QtCore.QRect(829, 5, 531, 20))
        self.repoBucketName.setObjectName("repoBucketName")
        self.repoBucketNameLabel = QtGui.QLabel(self.centralwidget)
        self.repoBucketNameLabel.setGeometry(QtCore.QRect(685, 5, 140, 20))
        self.repoBucketNameLabel.setObjectName("repoBucketNameLabel")
        self.dataBucketNameLabel = QtGui.QLabel(self.centralwidget)
        self.dataBucketNameLabel.setGeometry(QtCore.QRect(5, 5, 100, 20))
        self.dataBucketNameLabel.setObjectName("dataBucketNameLabel")
        self.dataBucketName = QtGui.QLineEdit(self.centralwidget)
        self.dataBucketName.setGeometry(QtCore.QRect(110, 5, 561, 20))
        self.dataBucketName.setObjectName("dataBucketName")
        self.progressMessagelabel = QtGui.QLabel(self.centralwidget)
        self.progressMessagelabel.setGeometry(QtCore.QRect(65, 285, 1285, 20))
        self.progressMessagelabel.setObjectName("progressMessagelabel")
        self.statusLabel = QtGui.QLabel(self.centralwidget)
        self.statusLabel.setGeometry(QtCore.QRect(5, 285, 50, 20))
        self.statusLabel.setObjectName("statusLabel")
        self.cancelButton = QtGui.QPushButton(self.centralwidget)
        self.cancelButton.setEnabled(False)
        self.cancelButton.setGeometry(QtCore.QRect(1175, 255, 170, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.progressBar = QtGui.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(5, 260, 1161, 20))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        OpenCloudRenderSubmit.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(OpenCloudRenderSubmit)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1370, 20))
        self.menubar.setObjectName("menubar")
        OpenCloudRenderSubmit.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(OpenCloudRenderSubmit)
        self.statusbar.setObjectName("statusbar")
        OpenCloudRenderSubmit.setStatusBar(self.statusbar)

        self.retranslateUi(OpenCloudRenderSubmit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenCloudRenderSubmit)

    def retranslateUi(self, OpenCloudRenderSubmit):
        OpenCloudRenderSubmit.setWindowTitle(QtGui.QApplication.translate("OpenCloudRenderSubmit", "OpenCloudRender", None, QtGui.QApplication.UnicodeUTF8))
        self.submitScenesButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "submit synced scenes", None, QtGui.QApplication.UnicodeUTF8))
        self.syncAssetsButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "sync assets", None, QtGui.QApplication.UnicodeUTF8))
        self.addScenesButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "add .vrscene/.ass files", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldVersionLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "default Arnold Version", None, QtGui.QApplication.UnicodeUTF8))
        self.dragDropOnlyLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "drag&drop only for now", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayVersionLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "default V-Ray Version", None, QtGui.QApplication.UnicodeUTF8))
        self.syncImagesButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "sync rendered images", None, QtGui.QApplication.UnicodeUTF8))
        self.mantraVersionLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "default Mantra Version", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.submissionTab), QtGui.QApplication.translate("OpenCloudRenderSubmit", "Submission", None, QtGui.QApplication.UnicodeUTF8))
        self.syncVrayRepoButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "sync Vray repo", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoRootDirLineEdit.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "/opt/vray", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoRootDirLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "local Vray repo", None, QtGui.QApplication.UnicodeUTF8))
        self.houdiniRepoRootDirLineEdit.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "/opt/", None, QtGui.QApplication.UnicodeUTF8))
        self.syncHoudiniRepoButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "sync Houdini repo", None, QtGui.QApplication.UnicodeUTF8))
        self.houdiniRepoRootDirLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "local Houdini repo", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRepoRootDirLineEdit.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "/opt/arnold", None, QtGui.QApplication.UnicodeUTF8))
        self.syncArnoldRepoButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "sync Arnold repo", None, QtGui.QApplication.UnicodeUTF8))
        self.arnoldRepoRootDirLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "local Arnold repo", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLineEdit.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "*docs*,*samples*", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "exclude:", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLineEdit_2.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "*toolkit*", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLabel_2.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "exclude:", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLineEdit_3.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "*noidea*", None, QtGui.QApplication.UnicodeUTF8))
        self.vrayRepoExcludesLabel_3.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "exclude:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.repoTab), QtGui.QApplication.translate("OpenCloudRenderSubmit", "Repositories", None, QtGui.QApplication.UnicodeUTF8))
        self.repoBucketNameLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "S3 Repository Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.dataBucketNameLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "S3 Data Bucket", None, QtGui.QApplication.UnicodeUTF8))
        self.progressMessagelabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "progressMessageLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "Status:", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelButton.setText(QtGui.QApplication.translate("OpenCloudRenderSubmit", "cancel", None, QtGui.QApplication.UnicodeUTF8))

